version: '3'
services:
  eureka-server:
    image: eureka-server
    container_name: hello-eureka-server:1.0
    expose:
    - "8761"
    ports: 
    - 8761:8761 
  emp-service:
    image: emp-microservice:1.0
    container_name: emp-service
    ports:
    - "8180-8188:8180"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://eureka-server:8761/eureka  #(name of eureka host==eureka container name)
      
    links: 
        - eureka-server
  dept-service:
    image: dept-microservice:1.0
    container_name: dept-service
    ports:
    - "8480-8488:8480"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://eureka-server:8761/eureka  #(name of eureka host==eureka container name)
      
    links: 
        - eureka-server
        
        
  hr-service:
    image: hr-service:1.0
    container_name: hr-service
    ports:
    - "8580-8588:8580"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://eureka-server:8761/eureka  #(name of eureka host==eureka container name)
      
    links: 
        - eureka-server

  gateway-service:
    image: -gateway-microservice:1.0
    container_name: gateway-service
    ports:
    - "9090-9098:9000"
    environment:
      - JAVA_OPTS=
            -DEUREKA_SERVER=http://eureka-server:8761/eureka  #(name of eureka host==eureka container name)
      
    links: 
        - eureka-server

        